### ISSUE TITLE
add iOS link

### ISSUE THREAD

**Issue by JAcup123** [kyou-nase/GI-Download-Library#7]
Where can I download the iOS version package.
I really need iOS package , because I am searching some way to play beta game on Mac OS .
Thank you soooo much

**Comment by JAcup123** [comment]
请求iOS版本的包体下载链接！
非常感谢！！

**Comment by rwx9032** [comment]
砸壳ipa可以去Playcover的dc群聊里面看看，Autopatch 没有ios的包

You can view it in Playcover's Discord group, Autopatch's packages without ios

这里是群聊里面的3.0.0的国服和国际的砸壳ipa

Here are the 3.0.0 CN and OS ipa in the group

来源非原神官方,请自辨文件是否含有恶意病毒

Source is not the official from Genshin ,Please identify if the file contains virus

Genshin Impact v3.0.0 CN links

https://ipa.playcover.workers.dev/0:/Genshin%20Impact/CN/%E5%8E%9F%E7%A5%9E_3.0.0.ipa
https://drive.google.com/file/d/1wHLymefwuDyppjDMrdx6QKks819PLfHF/view?usp=sharing
https://drive.google.com/file/d/1z07MQzyugyRG143SLnKNNJ_9mzFRKQ0b/view?usp=sharing

Genshin Impact v3.0.0 global links

https://ipa.playcover.workers.dev/0:/Genshin%20Impact/US/Genshin%20Impact_3.0.0.ipa
https://drive.google.com/file/d/1hwM4_GOnfBk8B-6uKCFpqwozAZ9_A8KX/view?usp=sharing
https://drive.google.com/file/d/10WUL39WsX05aemJwcmBULQiJh5geaxjD/view?usp=sharing

**Comment by JAcup123** [comment]
好的，非常感谢！！
大佬还是非常厉害了
